apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mission-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/borntoeatt/mission-control.git
    targetRevision: main
    path: .
    directory:
      include: "k8s.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: mission-control
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
